project:
  type: website
  output-dir: docs
  
website:
  title: "Max Feng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Viz"
        menu: 
          - href: us_solar.qmd
            text: "US Solar/Wind"
          - href: olympic_athletes_and_medals.qmd
            text: "Olympic Athletes and Medals"
      - href: text_analysis.qmd
        text: Text Analysis
      - href: simulation_analysis.qmd
        text: Simulation Analysis
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    
editor: visual

